project:
  type: website
  output-dir: docs

website:
  title: "DS334blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/LeifHarvey
format:
  html:
    theme: slate
    css: styles.css



